[package]
name = "coincell"
version = "0.1.0"
edition = "2024"

[dependencies]
display-info = "0.5.9"
eframe = "0.36.1"
image = "0.25.10"
interprocess = "2.4.2"
tray-icon = "0.24.2"
anyhow = "*"
directories = "6.0.0"
lazy_static = "1.5.0"
serde = { version = "1.0.229", features = ["derive", "rc"] }
toml = "1.1.4"
reqwest = { version = "0.13.4", features = ["blocking", "json", "form"] }
